# DGP Dev

In [8]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [986]:
from caml.extensions.synthetic_data import CamlSyntheticDataGenerator

In [987]:
data = CamlSyntheticDataGenerator(n_obs=10_000,
                                  n_cont_outcomes=0,
                                  n_binary_outcomes=1,
                                  n_cont_treatments=0,
                                  n_binary_treatments=0,
                                  n_discrete_treatments=1,
                                  n_cont_confounders=2, 
                                  n_binary_confounders=2,
                                  n_discrete_confounders=2,
                                  n_cont_heterogeneity_covariates=4,
                                  n_binary_heterogeneity_covariates=4,
                                  n_discrete_heterogeneity_covariates=4,
                                  n_heterogeneity_confounders=0,
                                  stddev_outcome_noise=3,
                                  stddev_treatment_noise=3,
                                  causal_model_functional_form="fully_non_linear",
                                  n_nonlinear_transformations=20,
                                  n_nonlinear_interactions=5,
                                  treatment_effect_weight=1,
                                  seed=None)

In [988]:
data.ates

                              Treatment       ATE
0  T1_discrete_on_Y1_binary_level_3_v_0  0.091549
1  T1_discrete_on_Y1_binary_level_2_v_0  0.090644
2  T1_discrete_on_Y1_binary_level_1_v_0  0.058711

In [989]:
data.df

,W1_continuous,W2_continuous,W1_binary,W2_binary,W1_discrete,W2_discrete,X1_continuous,X2_continuous,X3_continuous,X4_continuous,X1_binary,X2_binary,X3_binary,X4_binary,X1_discrete,X2_discrete,X3_discrete,X4_discrete,T1_discrete,Y1_binary
0,-0.417913,0.083724,0,0,7,0,1.925209,0.731911,0.365798,3.180425,1,1,0,1,2,8,2,2,3,1
1,-0.853330,0.738841,1,1,3,0,0.575789,0.211475,0.458917,8.904770,0,0,1,1,1,1,2,1,2,0
2,-2.188264,0.156935,1,0,10,0,1.473940,0.342793,0.509139,5.437614,0,0,0,0,2,1,0,3,2,0
3,-1.249025,0.327519,0,1,6,0,0.225843,0.324719,0.840587,1.512165,1,0,0,1,0,2,2,7,3,1
4,-1.144656,0.297264,0,1,13,2,3.112510,0.592202,0.947976,3.363788,1,0,1,1,2,4,1,5,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,-0.913823,0.397199,0,1,4,1,0.959931,0.260758,0.443283,4.554872,1,0,0,0,0,2,2,1,3,0
9996,-1.145766,0.353764,1,1,10,0,0.487663,0.466224,0.954425,1.746488,1,1,1,0,2,3,1,8,3,1
9997,-0.766492,0.165236,1,0,4,3,3.513776,0.615192,0.861193,7.550418,1,0,1,1,0,9,1,8,2,1
9998,-1.797627,0.222716,0,0,8,0,3.440967,0.169102,0.833349,3.470292,1,1,0,0,0,5,1,2,3,1
9999,-1.594185,0.246360,0,1,1,2,0.361496,0.644996,0.762738,4.616704,1,1,1,1,2,1,1,1,2,0

In [992]:
data.dgp['T1_discrete']

                         covariates  cat_1_params  cat_2_params transformation
0                     W1_continuous     -1.967478      0.237294        Softmax
1                     W2_continuous      1.880829      1.506282        Softmax
2                         W1_binary      2.058911     -2.148967        Softmax
3                         W2_binary     -1.646674     -1.836807        Softmax
4                       W1_discrete     -2.209301     -1.143428        Softmax
5                       W2_discrete     -0.323091      1.234825        Softmax
6                 sin_W2_continuous      2.893681     -0.818400        Softmax
7                 cos_W2_continuous     -2.521370     -2.296474        Softmax
8   2Dint_W1_discrete_W2_continuous     -0.213331     -2.795885        Softmax
9                    sqrt_W1_binary     -0.349760     -1.392811        Softmax
10                    sin_W2_binary      1.136381      2.040001        Softmax
11               square_W2_discrete      0.048388      1.874947        Softmax
12               sqrt_W1_continuous      1.242426     -2.879424        Softmax
13               sqrt_W2_continuous     -0.038146      2.667861        Softmax
14                 sqrt_W2_discrete     -1.887345     -1.670267        Softmax
15                  cos_W1_discrete      2.654502      1.106213        Softmax
16                   sqrt_W2_binary      0.884871      0.133334        Softmax
17                 square_W1_binary     -0.570780      1.991851        Softmax
18    2Dint_W1_binary_W2_continuous      2.045253     -1.485030        Softmax